version: '3.9'

services: 
    web:
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: gunicorn bookstore_project.wsgi -b 0.0.0.0:8000
        environment: 
            - SECRET_KEY=p_o3vp1rg5)t^lxm9-43%0)s-=1qpeq%o7gfq+e4#*!t+_ev82
            - DEBUG=1
            - ENVIRONMENT=development
            - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_51JIdCBIyeMaqWwjwCRg7Mgu4pIAXsg6XO0nzEVasNg1PDn8johGKyjlkENxkgByC83eP5daSamwP6SICLp6ppwn600LnGjl6Zv
            - STRIPE_TEST_SECRET_KEY=sk_test_51JIdCBIyeMaqWwjwOQO5dIPxFknlsETyoaF6l93tSEwL1beDM2YyjuPw8raFcSXNIWqEoJCDdC1pEF9vYUftiZDV00dfMicQXQ
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_DATA=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

volumes: 
    postgres_data:

    